Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -34,7 +34,22 @@ workflows:
            flutter test --coverage --machine > test-results/flutter.json  
            code_coverage=$(lcov --list $FCI_BUILD_DIR/coverage/lcov.info | sed -n "s/.*Total:|\(.*\)%.*/\1/p")
            echo "Code Coverage: ${code_coverage}% "
-           if (( $(echo "$code_coverage < $CODE_COVERAGE_TARGET" | bc) )); { then echo "Having trouble" && exit 1; }; fi  
+           if (( $(echo "$code_coverage < $CODE_COVERAGE_TARGET" | bc) )); then exit 1; fi  
+           
+           error() {
+            local parent_lineno="$1"
+            local message="$2"
+            local code="${3:-1}"
+            if [[ -n "$message" ]] ; then
+            echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
+            else
+            echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
+            fi
+            exit "${code}"
+            }
+            trap 'error ${LINENO}' ERR
+            
+            
         test_report: test-results/flutter.json
 
       - name: Codecov
