Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -36,7 +36,18 @@ workflows:
            echo "Code Coverage: ${code_coverage}% "
            if (( $(echo "$code_coverage < $CODE_COVERAGE_TARGET" | bc) )); then exit 1; fi  
            
-
+           error() {
+            local parent_lineno="$1"
+            local message="$2"
+            local code="${3:-1}"
+            if [[ -n "$message" ]] ; then
+            echo "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
+            else
+            echo "Error on or near line ${parent_lineno}; exiting with status ${code}"
+            fi
+            exit "${code}"
+            }
+            trap 'error ${LINENO}' ERR
             
             
         test_report: test-results/flutter.json
